SET @START_SPELL_ID := 33393;
SET @END_SPELL_ID := @START_SPELL_ID + 5;
DELETE FROM `spell_template` WHERE `Id` BETWEEN  @START_SPELL_ID AND @END_SPELL_ID;

SET @START_ITEM_ID := 25819;
SET @END_ITEM_ID := @START_ITEM_ID + 3;
DELETE FROM `item_template` WHERE `entry` BETWEEN  @START_ITEM_ID AND @END_ITEM_ID;
DELETE FROM `locales_item` WHERE `entry` BETWEEN  @START_ITEM_ID AND @END_ITEM_ID;
DELETE FROM `creature_loot_template` WHERE `item` BETWEEN  @START_ITEM_ID AND @END_ITEM_ID;