-- Spells
SET @START_SPELL_ID := 33393;
SET @END_SPELL_ID := @START_SPELL_ID + 5;
DELETE FROM `spell_template` WHERE `Id` BETWEEN  @START_SPELL_ID AND @END_SPELL_ID;
INSERT INTO `spell_template`            (`Id`,             `School`, `Category`, `CastUI`, `Dispel`, `Mechanic`, `Attributes`, `AttributesEx`, `AttributesEx2`, `AttributesEx3`, `AttributesEx4`, `Stances`, `StancesNot`, `Targets`, `TargetCreatureType`, `RequiresSpellFocus`, `CasterAuraState`, `TargetAuraState`, `CastingTimeIndex`, `RecoveryTime`, `CategoryRecoveryTime`, `InterruptFlags`, `AuraInterruptFlags`, `ChannelInterruptFlags`, `ProcFlags`, `ProcChance`, `ProcCharges`, `MaxLevel`, `BaseLevel`, `SpellLevel`, `DurationIndex`, `PowerType`, `ManaCost`, `ManaCostPerlevel`, `ManaPerSecond`, `ManaPerSecondPerLevel`, `RangeIndex`, `Speed`, `ModalNextSpell`, `StackAmount`, `Totem1`, `Totem2`, `Reagent1`, `Reagent2`, `Reagent3`, `Reagent4`, `Reagent5`, `Reagent6`, `Reagent7`, `Reagent8`, `ReagentCount1`, `ReagentCount2`, `ReagentCount3`, `ReagentCount4`, `ReagentCount5`, `ReagentCount6`, `ReagentCount7`, `ReagentCount8`, `EquippedItemClass`, `EquippedItemSubClassMask`, `EquippedItemInventoryTypeMask`, `Effect1`, `Effect2`, `Effect3`, `EffectDieSides1`, `EffectDieSides2`, `EffectDieSides3`, `EffectBaseDice1`, `EffectBaseDice2`, `EffectBaseDice3`, `EffectDicePerLevel1`, `EffectDicePerLevel2`, `EffectDicePerLevel3`, `EffectRealPointsPerLevel1`, `EffectRealPointsPerLevel2`, `EffectRealPointsPerLevel3`, `EffectBasePoints1`, `EffectBasePoints2`, `EffectBasePoints3`, `EffectMechanic1`, `EffectMechanic2`, `EffectMechanic3`, `EffectImplicitTargetA1`, `EffectImplicitTargetA2`, `EffectImplicitTargetA3`, `EffectImplicitTargetB1`, `EffectImplicitTargetB2`, `EffectImplicitTargetB3`, `EffectRadiusIndex1`, `EffectRadiusIndex2`, `EffectRadiusIndex3`, `EffectApplyAuraName1`, `EffectApplyAuraName2`, `EffectApplyAuraName3`, `EffectAmplitude1`, `EffectAmplitude2`, `EffectAmplitude3`, `EffectMultipleValue1`, `EffectMultipleValue2`, `EffectMultipleValue3`, `EffectChainTarget1`, `EffectChainTarget2`, `EffectChainTarget3`, `EffectItemType1`, `EffectItemType2`, `EffectItemType3`, `EffectMiscValue1`, `EffectMiscValue2`, `EffectMiscValue3`, `EffectTriggerSpell1`, `EffectTriggerSpell2`, `EffectTriggerSpell3`, `EffectPointsPerComboPoint1`, `EffectPointsPerComboPoint2`, `EffectPointsPerComboPoint3`, `SpellVisual`, `SpellIconID`, `ActiveIconID`, `SpellPriority`, `SpellName`,        `SpellName2`, `SpellName3`, `SpellName4`, `SpellName5`, `SpellName6`, `SpellName7`, `SpellName8`, `Rank1`,  `Rank2`, `Rank3`, `Rank4`, `Rank5`, `Rank6`, `Rank7`, `Rank8`, `ManaCostPercentage`, `StartRecoveryCategory`, `StartRecoveryTime`, `MaxTargetLevel`, `SpellFamilyName`, `SpellFamilyFlags`, `MaxAffectedTargets`, `DmgClass`, `PreventionType`, `StanceBarOrder`, `DmgMultiplier1`, `DmgMultiplier2`, `DmgMultiplier3`, `MinFactionId`, `MinReputation`, `RequiredAuraVision`, `EffectBonusCoefficient1`, `EffectBonusCoefficient2`, `EffectBonusCoefficient3`, `EffectBonusCoefficientFromAP1`, `EffectBonusCoefficientFromAP2`, `EffectBonusCoefficientFromAP3`, `IsServerSide`, `AttributesServerside`) VALUES 
-- Paladin
/* Crusader Strike           (33393) */ (@START_SPELL_ID,   0,        0,          0,        0,        0,          327680,       512,            0,               0,               0,               0,         0,            0,         0,                    0,                    0,                 0,                 1,                  6000,           0,                      0,                0,                    0,                       0,           101,          0,             0,          0,           1,            0,               0,           0,          0,                  0,               0,                       2,            0,       0,                0,             0,        0,        0,          0,          0,          0,          0,          0,          0,          0,          0,               0,               0,               0,               0,               0,               0,               0,               2,                   173555,                     0,                               31,        0,         0,         1,                 0,                 0,                 1,                 0,                 0,                 0,                     0,                     0,                     0,                           0,                           0,                           109,                 0,                   0,                   0,                 0,                 0,                 6,                        0,                        0,                        0,                        0,                        0,                        0,                    0,                    0,                    0,                      0,                      0,                      0,                  0,                  0,                  0,                      0,                      0,                      0,                    0,                    0,                    0,                 0,                 0,                 0,                  0,                  0,                  0,                     0,                     0,                     0,                            0,                            0,                            39,            237,           0,              0,              'Crusader Strike',   '',           '',           '',            '',          '',           '',           '',           '',       '',      '',      '',      '',      '',      '',      '',      9,                    133,                     1500,                0,                0,                 0,                  0,                    2,          2,                -1,               2,                1,                1,                0,              0,               0,                    0,                         0,                         0,                         0,                               0,                               0,                               0,              0),
/* Crusader Strike (learn)   (33394) */ (@START_SPELL_ID+1, 0,        0,          0,        0,        0,          256,          0,              0,               0,               0,               0,         0,            0,         0,                    0,                    0,                 0,                 14,                 0,              0,                      15,               0,                    0,                       0,           101,          0,             0,          0,           0,            0,               0,           0,          0,                  0,               0,                       1,            0,       0,                0,             0,        0,        0,          0,          0,          0,          0,          0,          0,          0,          0,               0,               0,               0,               0,               0,               0,               0,              -1,                   -1,                         0,                               36,        0,         0,         0,                 0,                 0,                 0,                 0,                 0,                 0,                     0,                     0,                     0,                           0,                           0,                           0,                   0,                   0,                   0,                 0,                 0,                 1,                        0,                        0,                        0,                        0,                        0,                        0,                    0,                    0,                    0,                      0,                      0,                      0,                  0,                  0,                  0,                      0,                      0,                      0,                    0,                    0,                    0,                 0,                 0,                 0,                  0,                  0,                  33393,                 0,                     0,                     0,                            0,                            0,                            222,           1,             0,              0,              'Crusader Strike',   '',           '',           '',            '',          '',           '',           '',           'Rank 1', '',      '',      '',      '',      '',      '',      '',      0,                    0,                       0,                   0,                0,                 0,                  0,                    1,          1,                -1,               1,                1,                1,                0,              0,               0,                    0,                         0,                         0,                         0,                               0,                               0,                               0,              0),
/* Hand of Reckoning         (33395) */ (@START_SPELL_ID+2, 0,        82,         0,        0,        0,          327696,       0,              67108864,        0,               0,               0,         0,            0,         0,                    0,                    0,                 0,                 1,                  0,              10000,                  0,                0,                    0,                       0,           101,          0,             0,          10,          10,           27,              0,           0,          0,                  0,               0,                       4,            0,       0,                0,             0,        0,        0,          0,          0,          0,          0,          0,          0,          0,          0,               0,               0,               0,               0,               0,               0,               0,              -1,                   -1,                         0,                               114,       6,         0,         0,                 0,                 0,                 0,                 0,                 0,                 0,                     0,                     0,                     0,                           0,                           0,                           0,                   0,                   0,                   0,                 0,                 0,                 6,                        6,                        0,                        0,                        0,                        0,                        0,                    0,                    0,                    0,                      11,                     0,                      0,                  0,                  0,                  0,                      0,                      0,                      0,                    0,                    0,                    0,                 0,                 0,                 0,                  0,                  0,                  0,                     0,                     0,                     0,                            0,                            0,                            34,            1823,          0,              0,              'Hand of Reckoning', '',           '',           '',            '',          '',           '',           '',           '',       '',      '',      '',      '',      '',      '',      '',      0,                    0,                       0,                   0,                4,                 32768,              0,                    1,          1,                -1,               1,                1,                1,                0,              0,               0,                    0,                         0,                         0,                         0,                               0,                               0,                               0,              0),
/* Hand of Reckoning (learn) (33396) */ (@START_SPELL_ID+3, 0,        0,          0,        0,        0,          256,          0,              0,               0,               0,               0,         0,            0,         0,                    0,                    0,                 0,                 14,                 0,              0,                      15,               0,                    0,                       0,           101,          0,             0,          0,           0,            0,               0,           0,          0,                  0,               0,                       1,            0,       0,                0,             0,        0,        0,          0,          0,          0,          0,          0,          0,          0,          0,               0,               0,               0,               0,               0,               0,               0,              -1,                   -1,                         0,                               36,        0,         0,         0,                 0,                 0,                 0,                 0,                 0,                 0,                     0,                     0,                     0,                           0,                           0,                           0,                   0,                   0,                   0,                 0,                 0,                 1,                        0,                        0,                        0,                        0,                        0,                        0,                    0,                    0,                    0,                      0,                      0,                      0,                  0,                  0,                  0,                      0,                      0,                      0,                    0,                    0,                    0,                 0,                 0,                 0,                  0,                  0,                  33395,                 0,                     0,                     0,                            0,                            0,                            222,           1,             0,              0,              'Hand of Reckoning', '',           '',           '',            '',          '',           '',           '',           'Rank 1', '',      '',      '',      '',      '',      '',      '',      0,                    0,                       0,                   0,                0,                 0,                  0,                    1,          1,                -1,               1,                1,                1,                0,              0,               0,                    0,                         0,                         0,                         0,                               0,                               0,                               0,              0),
-- Druid
/* Starfall                  (33397) */ (@START_SPELL_ID+4, 6,        0,          0,        0,        0,          65536,        268435592,      0,               0,               0,               0,         0,            0,         0,                    0,                    0,                 0,                 1,                  60000,          0,                      12,               0,                    0,                       0,           101,          0,             0,          1,           1,            1,               0,           0,          0,                  0,               0,                       4,            0,       0,                0,             0,        0,        0,          0,          0,          0,          0,          0,          0,          0,          0,               0,               0,               0,               0,               0,               0,               0,              -1,                   -1,                         0,                               27,        0,         0,         0,                 0,                 0,                 1,                 0,                 0,                 1.35,                  0,                     0,                     1.15,                        0,                           0,                           1,                   0,                   0,                   0,                 0,                 0,                 18,                       0,                        0,                        16,                       0,                        0,                        20,                   0,                    0,                    3,                      0,                      0,                      2000,               0,                  0,                  0,                      0,                      0,                      0,                    0,                    0,                    0,                 0,                 0,                 0,                  0,                  0,                  0,                     0,                     0,                     0,                            0,                            0,                            5780,          1485,          0,              50,             'Starfall',          '',           '',           '',            '',          '',           '',           '',           '',       '',      '',      '',      '',      '',      '',      '',      11,                   133,                     1500,                0,                7,                 4,                  0,                    1,          1,                -1,               1,                1,                1,                0,              0,               0,                    1,                         0,                         0,                         0,                               0,                               0,                               0,              0),
/* Starfall (learn)          (33398) */ (@START_SPELL_ID+5, 0,        0,          0,        0,        0,          256,          0,              0,               0,               0,               0,         0,            0,         0,                    0,                    0,                 0,                 14,                 0,              0,                      15,               0,                    0,                       0,           101,          0,             0,          0,           0,            0,               0,           0,          0,                  0,               0,                       1,            0,       0,                0,             0,        0,        0,          0,          0,          0,          0,          0,          0,          0,          0,               0,               0,               0,               0,               0,               0,               0,              -1,                   -1,                         0,                               36,        0,         0,         0,                 0,                 0,                 0,                 0,                 0,                 0,                     0,                     0,                     0,                           0,                           0,                           0,                   0,                   0,                   0,                 0,                 0,                 1,                        0,                        0,                        0,                        0,                        0,                        0,                    0,                    0,                    0,                      0,                      0,                      0,                  0,                  0,                  0,                      0,                      0,                      0,                    0,                    0,                    0,                 0,                 0,                 0,                  0,                  0,                  33397,                 0,                     0,                     0,                            0,                            0,                            222,           1,             0,              0,              'Starfall',          '',           '',           '',            '',          '',           '',           '',           'Rank 1', '',      '',      '',      '',      '',      '',      '',      0,                    0,                       0,                   0,                0,                 0,                  0,                    1,          1,                -1,               1,                1,                1,                0,              0,               0,                    0,                         0,                         0,                         0,                               0,                               0,                               0,              0);

-- Paladin
-- Benediction upgrade from 15% to 30%
UPDATE `spell_template` SET `EffectBasePoints1`= -7  WHERE `Id`= 20101;
UPDATE `spell_template` SET `EffectBasePoints1`= -13 WHERE `Id`= 20102;
UPDATE `spell_template` SET `EffectBasePoints1`= -19 WHERE `Id`= 20103;
UPDATE `spell_template` SET `EffectBasePoints1`= -25 WHERE `Id`= 20104;
UPDATE `spell_template` SET `EffectBasePoints1`= -31 WHERE `Id`= 20105;

-- Holy Shield increase block chance to 50% and reduce a 50% the mana cost
UPDATE `spell_template` SET `ManaCost`= 75,  `EffectBasePoints1`= 49 WHERE `Id`= 20925;
UPDATE `spell_template` SET `ManaCost`= 97,  `EffectBasePoints1`= 49 WHERE `Id`= 20927;
UPDATE `spell_template` SET `ManaCost`= 120, `EffectBasePoints1`= 49 WHERE `Id`= 20928;

-- Consecration reduce mana cost a 50%
UPDATE `spell_template` SET `ManaCost`= 67 WHERE  `Id`= 26573;
UPDATE `spell_template` SET `ManaCost`= 117 WHERE `Id`= 20116;
UPDATE `spell_template` SET `ManaCost`= 160 WHERE `Id`= 20922;
UPDATE `spell_template` SET `ManaCost`= 217 WHERE `Id`= 20923;
UPDATE `spell_template` SET `ManaCost`= 282 WHERE `Id`= 20924;

-- Blessings increase duration a 100%
UPDATE `spell_template` SET `DurationIndex`= 30 WHERE `Id`= 25898 OR `Id` = 25890 OR `Id` = 25782 OR `Id` = 25916 OR `Id` = 25895 OR `Id` = 25899 OR `Id` = 25894  OR `Id` = 25918;
UPDATE `spell_template` SET `DurationIndex`= 6 WHERE `Id`= 20217 OR `Id` = 19977 OR `Id` = 19978 OR `Id` = 19979 OR `Id` = 19740 OR `Id` = 19834 OR `Id` = 19835  OR `Id` = 19836 OR `Id` = 19837 OR `Id` = 19838 OR `Id` = 1038 OR `Id` = 20911 OR `Id` = 20912 OR `Id` = 20913  OR `Id` = 20914 OR `Id` = 19742 OR `Id` = 19850 OR `Id` = 19852 OR `Id` = 19853 OR `Id` = 19854  OR `Id` = 25290;

-- Hammer of Wrath cast time instant
UPDATE `spell_template` SET `CastingTimeIndex` = 1 WHERE `Id` = 24239 OR `Id` = 24274 OR `Id` = 24275;

-- Judgement different debuffs can be stacked
UPDATE `spell_template` SET `SpellFamilyFlags` = 0 WHERE Id = 20185 OR Id = 20344 OR Id = 20345 OR Id = 20346 OR Id = 20186 OR Id = 20354 OR Id = 20355 OR Id = 21183 OR Id = 20188 OR Id = 20300 OR Id = 20301 OR Id = 20302 OR Id = 20303 OR Id = 20184;

-- Druid
-- Natural Shapeshifter upgrade from 30% to 60%
UPDATE `spell_template` SET `EffectBasePoints1`= -21 WHERE `Id` = 16833;
UPDATE `spell_template` SET `EffectBasePoints1`= -41 WHERE `Id` = 16834;
UPDATE `spell_template` SET `EffectBasePoints1`= -61 WHERE `Id` = 16835;

-- Tiger's Fury reduce energy cost to 0 and add 30 seconds cooldown
UPDATE `spell_template` SET `RecoveryTime` = 30000, `ManaCost` = 0 WHERE `Id` = 5217 OR `Id` = 6793 OR `Id` = 9845 OR `Id` = 9846;

-- Savage Fury will also increase bleed damage up to a 30%
UPDATE `spell_template` SET `EffectBasePoints1`= 14, `EffectBasePoints2`= 14 WHERE `Id`=16998;
UPDATE `spell_template` SET `EffectBasePoints1`= 29, `EffectBasePoints2`= 29 WHERE `Id`=16999;
UPDATE `spell_template` SET `SpellFamilyFlags`= 8392704 WHERE `Id`= 1079 OR `Id`= 9492 OR `Id`= 9493 OR `Id`= 9752 OR `Id`= 9894 OR `Id`= 9896; -- Rip
UPDATE `spell_template` SET `SpellFamilyName`= 7, `SpellFamilyFlags`= 4096 WHERE `Id`= 9007 OR `Id`= 9824 OR `Id`= 9826; -- Pounce

-- Shaman
-- Convection upgrade from 10% to 30%
UPDATE `spell_template` SET `EffectBasePoints1`= -7  WHERE `Id`= 16039;
UPDATE `spell_template` SET `EffectBasePoints1`= -13 WHERE `Id`= 16109;
UPDATE `spell_template` SET `EffectBasePoints1`= -19 WHERE `Id`= 16110;
UPDATE `spell_template` SET `EffectBasePoints1`= -25 WHERE `Id`= 16111;
UPDATE `spell_template` SET `EffectBasePoints1`= -31 WHERE `Id`= 16112;

-- Hunter
-- Efficiency upgrade from 10% to 30%
UPDATE `spell_template` SET `EffectBasePoints1`= -7  WHERE `Id`= 19416;
UPDATE `spell_template` SET `EffectBasePoints1`= -13 WHERE `Id`= 19417;
UPDATE `spell_template` SET `EffectBasePoints1`= -19 WHERE `Id`= 19418;
UPDATE `spell_template` SET `EffectBasePoints1`= -25 WHERE `Id`= 19419;
UPDATE `spell_template` SET `EffectBasePoints1`= -31 WHERE `Id`= 19420;

-- Items
SET @START_ITEM_ID := 25819;
SET @END_ITEM_ID := @START_ITEM_ID + 3;
DELETE FROM `item_template` WHERE `entry` BETWEEN  @START_ITEM_ID AND @END_ITEM_ID;
INSERT INTO `item_template`           (`entry`,         `class`, `subclass`, `name`,                   `displayid`, `Quality`, `Flags`, `BuyCount`, `BuyPrice`, `SellPrice`, `InventoryType`, `AllowableClass`, `AllowableRace`, `ItemLevel`, `RequiredLevel`, `RequiredSkill`, `RequiredSkillRank`, `requiredspell`, `requiredhonorrank`, `RequiredCityRank`, `RequiredReputationFaction`, `RequiredReputationRank`, `maxcount`, `stackable`, `ContainerSlots`, `stat_type1`, `stat_value1`, `stat_type2`, `stat_value2`, `stat_type3`, `stat_value3`, `stat_type4`, `stat_value4`, `stat_type5`, `stat_value5`, `stat_type6`, `stat_value6`, `stat_type7`, `stat_value7`, `stat_type8`, `stat_value8`, `stat_type9`, `stat_value9`, `stat_type10`, `stat_value10`, `dmg_min1`, `dmg_max1`, `dmg_type1`, `dmg_min2`, `dmg_max2`, `dmg_type2`, `dmg_min3`, `dmg_max3`, `dmg_type3`, `dmg_min4`, `dmg_max4`, `dmg_type4`, `dmg_min5`, `dmg_max5`, `dmg_type5`, `armor`, `holy_res`, `fire_res`, `nature_res`, `frost_res`, `shadow_res`, `arcane_res`, `delay`, `ammo_type`, `RangedModRange`, `spellid_1`, `spelltrigger_1`, `spellcharges_1`, `spellppmRate_1`, `spellcooldown_1`, `spellcategory_1`, `spellcategorycooldown_1`, `spellid_2`, `spelltrigger_2`, `spellcharges_2`, `spellppmRate_2`, `spellcooldown_2`, `spellcategory_2`, `spellcategorycooldown_2`, `spellid_3`, `spelltrigger_3`, `spellcharges_3`, `spellppmRate_3`, `spellcooldown_3`, `spellcategory_3`, `spellcategorycooldown_3`, `spellid_4`, `spelltrigger_4`, `spellcharges_4`, `spellppmRate_4`, `spellcooldown_4`, `spellcategory_4`, `spellcategorycooldown_4`, `spellid_5`, `spelltrigger_5`, `spellcharges_5`, `spellppmRate_5`, `spellcooldown_5`, `spellcategory_5`, `spellcategorycooldown_5`, `bonding`, `description`, `PageText`, `LanguageID`, `PageMaterial`, `startquest`, `lockid`, `Material`, `sheath`, `RandomProperty`, `block`, `itemset`, `MaxDurability`, `area`, `Map`, `BagFamily`, `ScriptName`, `DisenchantID`, `FoodType`, `minMoneyLoot`, `maxMoneyLoot`, `Duration`, `ExtraFlags`) VALUES 
-- Paladin spell books
/* Book: Crusader Strike   (25819) */ (@START_ITEM_ID,   9,       0,         'Book: Crusader Strike',   1317,        3,         64,      1,          35000,      8750,        0,               2,               -1,               50,          1,               0,               0,                   0,               0,                   0,                  0,                           0,                        0,          1,           0,                0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,             0,              0,          0,          0,           0,          0,          0,           0,          0,          0,           0,          0,          0,           0,          0,          0,           0,       0,          0,          0,            0,           0,            0,            0,       0,           0,                33394,       0,                -1,               0,                -1,                0,                 -1,                        0,           0,                0,                0,                -1,                0,                 -1,                        0,           0,                0,                0,                -1,                0,                 -1,                        0,           0,                0,                0,                -1,                0,                 -1,                        0,           0,                0,                0,                0,                 0,                 0,                         0,         '',            0,          0,            0,              0,            0,        0,          0,        0,                0,       0,         0,               0,      0,     0,           '',           0,              0,          0,              0,              0,          0),
/* Book: Hand of Reckoning (25820) */ (@START_ITEM_ID+1, 9,       0,         'Book: Hand of Reckoning', 1317,        3,         64,      1,          35000,      8750,        0,               2,               -1,               50,          1,               0,               0,                   0,               0,                   0,                  0,                           0,                        0,          1,           0,                0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,             0,              0,          0,          0,           0,          0,          0,           0,          0,          0,           0,          0,          0,           0,          0,          0,           0,       0,          0,          0,            0,           0,            0,            0,       0,           0,                33396,       0,                -1,               0,                -1,                0,                 -1,                        0,           0,                0,                0,                -1,                0,                 -1,                        0,           0,                0,                0,                -1,                0,                 -1,                        0,           0,                0,                0,                -1,                0,                 -1,                        0,           0,                0,                0,                0,                 0,                 0,                         0,         '',            0,          0,            0,              0,            0,        0,          0,        0,                0,       0,         0,               0,      0,     0,           '',           0,              0,          0,              0,              0,          0),
-- Druid spell books
/* Book: Starfall          (25821) */ (@START_ITEM_ID+2, 9,       0,         'Book: Starfall',          1317,        3,         64,      1,          35000,      8750,        0,               1024,            -1,               50,          1,               0,               0,                   0,               0,                   0,                  0,                           0,                        0,          1,           0,                0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,            0,             0,             0,              0,          0,          0,           0,          0,          0,           0,          0,          0,           0,          0,          0,           0,          0,          0,           0,       0,          0,          0,            0,           0,            0,            0,       0,           0,                33398,       0,                -1,               0,                -1,                0,                 -1,                        0,           0,                0,                0,                -1,                0,                 -1,                        0,           0,                0,                0,                -1,                0,                 -1,                        0,           0,                0,                0,                -1,                0,                 -1,                        0,           0,                0,                0,                0,                 0,                 0,                         0,         '',            0,          0,            0,              0,            0,        0,          0,        0,                0,       0,         0,               0,      0,     0,           '',           0,              0,          0,              0,              0,          0);

-- Items locale
DELETE FROM `locales_item` WHERE `entry` BETWEEN  @START_ITEM_ID AND @END_ITEM_ID;
INSERT INTO `locales_item`            (`entry`,         `name_loc1`, `name_loc2`, `name_loc3`, `name_loc4`, `name_loc5`, `name_loc6`,                  `name_loc7`, `name_loc8`, `description_loc1`, `description_loc2`, `description_loc3`, `description_loc4`, `description_loc5`, `description_loc6`, `description_loc7`, `description_loc8`) VALUES 
-- Paladin spell books
/* Book: Crusader Strike   (25819) */ (@START_ITEM_ID,   '',          '',          '',          '',          '',         'Libro: Golpe del Cruzado',   '',          '',          '',                 '',                 '',                 '',                 '',                 '',                 '',                 ''),
/* Book: Hand of Reckoning (25820) */ (@START_ITEM_ID+1, '',          '',          '',          '',          '',         'Libro: Mano de expiación',   '',          '',          '',                 '',                 '',                 '',                 '',                 '',                 '',                 ''),
-- Druid spell books
/* Book: Starfall          (25821) */ (@START_ITEM_ID+2, '',          '',          '',          '',          '',         'Libro: Estrella caída',      '',          '',          '',                 '',                 '',                 '',                 '',                 '',                 '',                 '');

-- Loot tables
DELETE FROM `creature_loot_template` WHERE `item` BETWEEN  @START_ITEM_ID AND @END_ITEM_ID;
INSERT INTO `creature_loot_template`                    (`entry`, `item`,            `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`, `condition_id`, `comments`) VALUES 
-- Paladin spell books
/* Book: Crusader Strike   (25819) on Herod  (3975) */ 	(3975,     @START_ITEM_ID,    35,                    0,         1,               1,          0,             'Book: Crusader Strike'),
/* Book: Hand of Reckoning (25820) on Vishas (3983) */ 	(3975,     @START_ITEM_ID+1,  35,                    0,         1,               1,          0,             'Book: Hand of Reckoning'),
-- Druid spell books
/* Book: Starfall          (25821) on Mutanus (3654) */ (3654,     @START_ITEM_ID+2,  35,                    0,         1,               1,          0,             'Book: Starfall');
